const STATES = [
  {st:"AL",name:"Alabama",cl:"ala",court:"Supreme Court of Alabama",url:"https://judicial.alabama.gov/"},
  {st:"AK",name:"Alaska",cl:"alaska",court:"Alaska Supreme Court",url:"https://courts.alaska.gov/"},
  {st:"AZ",name:"Arizona",cl:"ariz",court:"Arizona Supreme Court",url:"https://www.azcourts.gov/"},
  {st:"AR",name:"Arkansas",cl:"ark",court:"Supreme Court of Arkansas",url:"https://courts.arkansas.gov/"},
  {st:"CA",name:"California",cl:"cal",court:"California Supreme Court",url:"https://www.courts.ca.gov/"},
  {st:"CO",name:"Colorado",cl:"colo",court:"Supreme Court of Colorado",url:"https://www.courts.state.co.us/"},
  {st:"CT",name:"Connecticut",cl:"conn",court:"Supreme Court of Connecticut",url:"https://www.jud.ct.gov/"},
  {st:"DE",name:"Delaware",cl:"del",court:"Supreme Court of Delaware",url:"https://courts.delaware.gov/"},
  {st:"DC",name:"District of Columbia",cl:"dc",court:"D.C. Court of Appeals",url:"https://www.dccourts.gov/"},
  {st:"FL",name:"Florida",cl:"fla",court:"Supreme Court of Florida",url:"https://www.floridasupremecourt.org/"},
  {st:"GA",name:"Georgia",cl:"ga",court:"Supreme Court of Georgia",url:"https://www.gasupreme.us/"},
  {st:"HI",name:"Hawaii",cl:"haw",court:"Hawaii Supreme Court",url:"https://www.courts.state.hi.us/"},
  {st:"ID",name:"Idaho",cl:"idaho",court:"Idaho Supreme Court",url:"https://isc.idaho.gov/"},
  {st:"IL",name:"Illinois",cl:"ill",court:"Illinois Supreme Court",url:"https://www.illinoiscourts.gov/"},
  {st:"IN",name:"Indiana",cl:"ind",court:"Indiana Supreme Court",url:"https://www.in.gov/courts/"},
  {st:"IA",name:"Iowa",cl:"iowa",court:"Supreme Court of Iowa",url:"https://www.iowacourts.gov/"},
  {st:"KS",name:"Kansas",cl:"kan",court:"Supreme Court of Kansas",url:"https://www.kscourts.gov/"},
  {st:"KY",name:"Kentucky",cl:"ky",court:"Kentucky Supreme Court",url:"https://www.kycourts.gov/"},
  {st:"LA",name:"Louisiana",cl:"la",court:"Supreme Court of Louisiana",url:"https://www.lasc.org/"},
  {st:"ME",name:"Maine",cl:"me",court:"Supreme Judicial Court of Maine",url:"https://www.courts.maine.gov/"},
  {st:"MD",name:"Maryland",cl:"md",court:"Supreme Court of Maryland",url:"https://www.mdcourts.gov/"},
  {st:"MA",name:"Massachusetts",cl:"mass",court:"Massachusetts Supreme Judicial Court",url:"https://www.mass.gov/orgs/massachusetts-supreme-judicial-court"},
  {st:"MI",name:"Michigan",cl:"mich",court:"Michigan Supreme Court",url:"https://www.courts.michigan.gov/"},
  {st:"MN",name:"Minnesota",cl:"minn",court:"Supreme Court of Minnesota",url:"https://www.mncourts.gov/"},
  {st:"MS",name:"Mississippi",cl:"miss",court:"Mississippi Supreme Court",url:"https://courts.ms.gov/"},
  {st:"MO",name:"Missouri",cl:"mo",court:"Supreme Court of Missouri",url:"https://www.courts.mo.gov/"},
  {st:"MT",name:"Montana",cl:"mont",court:"Montana Supreme Court",url:"https://courts.mt.gov/"},
  {st:"NE",name:"Nebraska",cl:"neb",court:"Nebraska Supreme Court",url:"https://supremecourt.nebraska.gov/"},
  {st:"NV",name:"Nevada",cl:"nev",court:"Nevada Supreme Court",url:"https://nvcourts.gov/"},
  {st:"NH",name:"New Hampshire",cl:"nh",court:"Supreme Court of New Hampshire",url:"https://www.courts.nh.gov/"},
  {st:"NJ",name:"New Jersey",cl:"nj",court:"Supreme Court of New Jersey",url:"https://www.njcourts.gov/"},
  {st:"NM",name:"New Mexico",cl:"nm",court:"New Mexico Supreme Court",url:"https://nmsupremecourt.nmcourts.gov/"},
  {st:"NY",name:"New York",cl:"ny",court:"New York Court of Appeals",url:"https://www.nycourts.gov/"},
  {st:"NC",name:"North Carolina",cl:"nc",court:"Supreme Court of North Carolina",url:"https://www.nccourts.gov/"},
  {st:"ND",name:"North Dakota",cl:"nd",court:"North Dakota Supreme Court",url:"https://www.ndcourts.gov/"},
  {st:"OH",name:"Ohio",cl:"ohio",court:"Supreme Court of Ohio",url:"https://www.supremecourt.ohio.gov/"},
  {st:"OK",name:"Oklahoma",cl:"okla",court:"Supreme Court of Oklahoma",url:"https://www.oscn.net/"},
  {st:"OR",name:"Oregon",cl:"or",court:"Oregon Supreme Court",url:"https://www.courts.oregon.gov/"},
  {st:"PA",name:"Pennsylvania",cl:"pa",court:"Supreme Court of Pennsylvania",url:"https://www.pacourts.us/"},
  {st:"RI",name:"Rhode Island",cl:"ri",court:"Supreme Court of Rhode Island",url:"https://www.courts.ri.gov/"},
  {st:"SC",name:"South Carolina",cl:"sc",court:"Supreme Court of South Carolina",url:"https://www.sccourts.org/"},
  {st:"SD",name:"South Dakota",cl:"sd",court:"South Dakota Supreme Court",url:"https://ujs.sd.gov/"},
  {st:"TN",name:"Tennessee",cl:"tenn",court:"Tennessee Supreme Court",url:"https://www.tncourts.gov/"},
  {st:"TX",name:"Texas",cl:"tex",court:"Supreme Court of Texas",url:"https://www.txcourts.gov/"},
  {st:"UT",name:"Utah",cl:"utah",court:"Utah Supreme Court",url:"https://www.utcourts.gov/"},
  {st:"VT",name:"Vermont",cl:"vt",court:"Supreme Court of Vermont",url:"https://www.vermontjudiciary.org/"},
  {st:"VA",name:"Virginia",cl:"va",court:"Supreme Court of Virginia",url:"https://www.vacourts.gov/"},
  {st:"WA",name:"Washington",cl:"wash",court:"Washington Supreme Court",url:"https://www.courts.wa.gov/"},
  {st:"WV",name:"West Virginia",cl:"wva",court:"West Virginia Supreme Court",url:"https://www.courtswv.gov/"},
  {st:"WI",name:"Wisconsin",cl:"wis",court:"Wisconsin Supreme Court",url:"https://www.wicourts.gov/"},
  {st:"WY",name:"Wyoming",cl:"wyo",court:"Wyoming Supreme Court",url:"https://www.courts.state.wy.us/"}
];
function stateByCode(st){return STATES.find(s=>s.st===st)||STATES.find(s=>s.st==="IL");}
